### PR TITLE
merge pipelines and clean up

### PR DESCRIPTION
**Pull request by Chunmingl**

### CODE REVIEW

**Comment by gaow** [comment]
@Chunmingl this file `code/pecotmr_integration/python.ipynb` is it necessary?

**Comment by Chunmingl** [comment]
This file is removed

**Comment by gaow** [comment]
okay for ctwas the codes are also all commented out. I think at this point we should try to test the cTWAS codes and see if it works? Also does ctwas really depends on `sos_variable(regional_data)` because i have not seen it used?

**Comment by Chunmingl** [comment]
the sos variables were updated after testing on twas and ctwas pipelines together

**Pull request merged**
